"""
main.py — FastAPI Backend Server for the SRX Platform

FILE LOCATION: Save this file as:
    ~/Desktop/srx-platform/backend/main.py

HOW TO START THE SERVER:
    cd ~/Desktop/srx-platform
    source venv/bin/activate
    python3 -m uvicorn backend.main:app --reload --port 8000

    Then open http://localhost:8000 in your browser to confirm it's running.
    You'll see a JSON response listing all available endpoints.

    Interactive API docs (auto-generated by FastAPI):
      http://localhost:8000/docs

ARCHITECTURE — TWO OPTIONS:

    Option 1 (RECOMMENDED for beginners — what this project uses):
        dashboard.py calls the FastAPI server using the "requests" library
        over HTTP. This simulates a real backend/frontend architecture where
        the dashboard and backend are separate services.

        How it works:
            Terminal 1: uvicorn runs the backend on port 8000
            Terminal 2: streamlit runs the dashboard on port 8501
            The dashboard sends HTTP GET requests like:
                response = requests.get("http://localhost:8000/pri?tickers=SPY,TLT")
            and displays the JSON response.

        Pros: Realistic architecture. Backend and frontend can be developed
              independently. Easy to test endpoints in a browser.
        Cons: Requires two terminal windows running simultaneously.

    Option 2 (Simpler but less realistic):
        dashboard.py imports the engine functions directly:
            from backend.portfolio_engine import calculate_pri
            result = calculate_pri(["SPY","TLT"], [0.6,0.4])
        No FastAPI server needed. One terminal only.

        Pros: Simpler to run (one command).
        Cons: Not how real systems work. Harder to test individual endpoints.

    This project uses Option 1 because it teaches real-world architecture
    while still being beginner-friendly.

ALL ENDPOINTS:

    Original (used by the dashboard):
      GET /          → Server health check
      GET /pri       → Portfolio Risk Index
      GET /srs       → Systemic Risk Scores per asset
      GET /gsri      → Global Systemic Risk Index
      GET /stress    → Portfolio stress testing
      GET /price     → Crash protection pricing
      GET /waterfall → Default waterfall simulation
      GET /gating    → Dynamic gating status

    New endpoints (added in this version):
      GET /health              → Detailed health check with component status
      GET /market-data         → Raw market prices, returns, volume
      GET /portfolio-risk      → Combined PRI + SRS analysis
      GET /srs-gsri            → Combined SRS + GSRI snapshot
      GET /price-protection    → Alias for /price with POST support
      GET /run-waterfall-stress-test → Clearinghouse stress test by magnitude
"""

import sys
import os
import time

# Add the project root to the path so we can import our modules.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

# ---- Import FastAPI ----
try:
    from fastapi import FastAPI, Query
    from fastapi.middleware.cors import CORSMiddleware
    from pydantic import BaseModel, Field
except ImportError:
    raise ImportError(
        "\n\n"
        "ERROR: FastAPI is not installed.\n"
        "Fix: Run this command in your terminal:\n"
        "  pip install fastapi uvicorn\n"
    )

# ---- Import SRX engine modules ----
try:
    from backend.portfolio_engine import calculate_pri, calculate_srs, run_stress_test
    from backend.gsri_engine import calculate_gsri
    from backend.pricing_engine import price_protection, price_protection_grid
    from backend.clearinghouse_simulation import (
        simulate_default_waterfall, evaluate_gating,
        run_stress_test as waterfall_stress_test,
    )
    from backend.gating_engine import evaluate_srs_gate, get_margin_multiplier
    from data.market_data import (
        get_market_prices, get_market_returns, get_market_volume,
        SRX_CORE_TICKERS,
    )
except ImportError as e:
    print(
        f"\n"
        f"ERROR importing SRX modules: {e}\n"
        f"\n"
        f"Possible fixes:\n"
        f"  1. Make sure you're running from the srx-platform folder\n"
        f"  2. Make sure all __init__.py files exist in backend/ and data/\n"
        f"  3. Run: pip install -r requirements.txt\n"
    )
    raise


# =============================================================================
# PYDANTIC MODELS — request/response validation
# =============================================================================

class ProtectionRequest(BaseModel):
    """Request body for POST /price-protection."""
    tickers: list = Field(
        default=["SPY", "HYG", "TLT", "GLD", "BTC-USD"],
        description="List of ticker symbols",
        examples=[["SPY", "HYG", "TLT", "GLD", "BTC-USD"]],
    )
    weights: list = Field(
        default=None,
        description="Portfolio weights (must sum to 1.0). If null, equal weight.",
        examples=[[0.40, 0.20, 0.20, 0.10, 0.10]],
    )
    notional: float = Field(
        default=1_000_000,
        description="Portfolio value in dollars",
        ge=1000,
    )
    protection_level_pct: float = Field(
        default=20.0,
        description="Drawdown trigger level (%)",
        gt=0, le=100,
    )
    duration_days: int = Field(
        default=90,
        description="Contract duration in calendar days",
        gt=0,
    )
    period: str = Field(
        default="2y",
        description="Historical data period",
    )


# =============================================================================
# CREATE THE APP
# =============================================================================

# Record the server start time (for the health check).
SERVER_START_TIME = time.time()

app = FastAPI(
    title="SRX Platform — Systemic Risk Exchange",
    description=(
        "Research prototype API for systemic risk analytics and crash protection pricing. "
        "All endpoints return JSON. Use /docs for interactive documentation."
    ),
    version="0.2.0",
)

# Allow the Streamlit dashboard (running on port 8501) to talk to this server.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# =============================================================================
# HELPER: parse tickers and weights from query strings
# =============================================================================

def _parse_tickers(tickers: str) -> list:
    """Parse a comma-separated ticker string into a clean uppercase list."""
    return [t.strip().upper() for t in tickers.split(",") if t.strip()]


def _parse_weights(weights: str) -> list:
    """Parse a comma-separated weight string into a list of floats. Returns None if empty."""
    if not weights or not weights.strip():
        return None
    try:
        return [float(w.strip()) for w in weights.split(",")]
    except ValueError:
        return None


# =============================================================================
# ORIGINAL ENDPOINTS (backward compatible — dashboard uses these)
# =============================================================================

@app.get("/")
def root():
    """
    Home page — confirms the server is running and lists all endpoints.

    Example response:
    {
        "status": "SRX Platform is running",
        "version": "0.2.0",
        "endpoints": {
            "original": ["/pri", "/srs", "/gsri", "/stress", "/price", "/waterfall", "/gating"],
            "new": ["/health", "/market-data", "/portfolio-risk", "/srs-gsri",
                    "/price-protection", "/run-waterfall-stress-test"]
        }
    }
    """
    return {
        "status": "SRX Platform is running",
        "version": "0.2.0",
        "docs": "Visit /docs for interactive API documentation",
        "endpoints": {
            "original": ["/pri", "/srs", "/gsri", "/stress", "/price", "/waterfall", "/gating"],
            "new": ["/health", "/market-data", "/portfolio-risk", "/srs-gsri",
                    "/price-protection", "/run-waterfall-stress-test"],
        },
    }


@app.get("/pri")
def get_pri(
    tickers: str = "SPY,QQQ,TLT,GLD",
    weights: str = None,
    period: str = "2y",
):
    """
    Calculate Portfolio Risk Index.

    Example: /pri?tickers=SPY,TLT,GLD&weights=0.5,0.3,0.2
    """
    ticker_list = _parse_tickers(tickers)
    weight_list = _parse_weights(weights)
    if weights and weight_list is None:
        return {"error": "Weights must be numbers separated by commas. Example: 0.5,0.3,0.2"}
    return calculate_pri(ticker_list, weight_list, period)


@app.get("/srs")
def get_srs(
    tickers: str = "SPY,QQQ,IWM,EFA,EEM,TLT,HYG,GLD,VNQ",
    market_ticker: str = "SPY",
    period: str = "2y",
):
    """Calculate Systemic Risk Scores for each asset."""
    return calculate_srs(_parse_tickers(tickers), market_ticker, period)


@app.get("/gsri")
def get_gsri(
    period: str = "2y",
    rolling_window: int = 60,
):
    """Calculate the Global Systemic Risk Index."""
    return calculate_gsri(period=period, rolling_window=rolling_window)


@app.get("/stress")
def get_stress_test(
    tickers: str = "SPY,QQQ,TLT,GLD",
    weights: str = None,
    scenario: str = "2008_crisis",
    custom_shock_pct: float = None,
    period: str = "2y",
):
    """
    Run a portfolio stress test.

    Scenarios: 2008_crisis, covid_crash, rate_shock,
               liquidity_freeze, crypto_contagion, custom
    """
    ticker_list = _parse_tickers(tickers)
    weight_list = _parse_weights(weights)
    if weights and weight_list is None:
        return {"error": "Weights must be numbers separated by commas."}
    return run_stress_test(ticker_list, weight_list, scenario, custom_shock_pct, period)


@app.get("/price")
def get_price(
    tickers: str = "SPY,QQQ,TLT,GLD",
    weights: str = None,
    notional: float = 1_000_000,
    protection_level_pct: float = 20.0,
    duration_days: int = 90,
    period: str = "2y",
):
    """Price a crash protection contract."""
    ticker_list = _parse_tickers(tickers)
    weight_list = _parse_weights(weights)
    if weights and weight_list is None:
        return {"error": "Weights must be numbers separated by commas."}
    return price_protection(
        ticker_list, weight_list, notional,
        protection_level_pct, duration_days, period,
    )


@app.get("/waterfall")
def get_waterfall(
    defaulter_margin: float = 500_000,
    defaulter_guarantee_fund: float = 200_000,
    platform_capital: float = 1_000_000,
    other_members_guarantee_fund: float = 3_000_000,
    emergency_assessment_capacity: float = 2_000_000,
    loss_amount: float = 2_500_000,
):
    """Simulate a default waterfall."""
    return simulate_default_waterfall(
        defaulter_margin, defaulter_guarantee_fund,
        platform_capital, other_members_guarantee_fund,
        emergency_assessment_capacity, loss_amount,
    )


@app.get("/gating")
def get_gating(
    gsri_score: float = None,
    portfolio_pri: float = None,
    recent_volatility_pct: float = None,
):
    """
    Evaluate dynamic gating level.
    If gsri_score is not provided, it will be calculated live.
    """
    if gsri_score is None:
        gsri_result = calculate_gsri()
        if "error" in gsri_result:
            return {"error": f"Could not calculate GSRI for gating: {gsri_result['error']}"}
        gsri_score = gsri_result["current_gsri"]
    return evaluate_gating(gsri_score, portfolio_pri, recent_volatility_pct)


# =============================================================================
# NEW ENDPOINTS
# =============================================================================

@app.get("/health")
def health_check():
    """
    Detailed health check with component status.

    Returns server uptime, version, and whether each engine module
    is importable and functional.

    Example response:
    {
        "status": "healthy",
        "version": "0.2.0",
        "uptime_seconds": 1234,
        "components": {
            "portfolio_engine": "ok",
            "gsri_engine": "ok",
            "pricing_engine": "ok",
            "stress_engine": "ok",
            "clearinghouse": "ok",
            "gating_engine": "ok",
            "market_data": "ok"
        }
    }
    """
    uptime = round(time.time() - SERVER_START_TIME, 1)
    components = {}

    # Check each module is importable and has its key function.
    checks = [
        ("portfolio_engine", "backend.portfolio_engine", "calculate_pri"),
        ("gsri_engine", "backend.gsri_engine", "calculate_gsri"),
        ("pricing_engine", "backend.pricing_engine", "price_protection"),
        ("stress_engine", "backend.stress_engine", "run_stress_test"),
        ("clearinghouse", "backend.clearinghouse_simulation", "simulate_default_waterfall"),
        ("gating_engine", "backend.gating_engine", "evaluate_srs_gate"),
        ("market_data", "data.market_data", "get_market_prices"),
    ]

    all_ok = True
    for name, module_path, func_name in checks:
        try:
            import importlib
            mod = importlib.import_module(module_path)
            if hasattr(mod, func_name):
                components[name] = "ok"
            else:
                components[name] = f"warning: {func_name} not found"
                all_ok = False
        except Exception as e:
            components[name] = f"error: {e}"
            all_ok = False

    return {
        "status": "healthy" if all_ok else "degraded",
        "version": "0.2.0",
        "uptime_seconds": uptime,
        "components": components,
    }


@app.get("/market-data")
def get_market_data(
    tickers: str = None,
    period: str = "2y",
    data_type: str = Query(
        default="prices",
        description="Type of data: 'prices', 'returns', or 'volume'",
    ),
):
    """
    Get raw market data (prices, returns, or volume).

    Parameters:
        tickers: Comma-separated ticker symbols. If empty, uses SRX core tickers.
        period: Historical period (1y, 2y, 5y).
        data_type: One of "prices", "returns", or "volume".

    Example: /market-data?tickers=SPY,TLT,GLD&data_type=returns&period=1y

    Example response (truncated):
    {
        "data_type": "prices",
        "tickers": ["SPY", "TLT", "GLD"],
        "rows": 502,
        "date_range": {"start": "2023-03-08", "end": "2025-03-07"},
        "latest_values": {"SPY": 567.82, "TLT": 87.34, "GLD": 271.50},
        "data": [{"date": "2023-03-08", "SPY": 380.12, "TLT": 102.5, "GLD": 168.3}, ...]
    }
    """
    try:
        ticker_list = _parse_tickers(tickers) if tickers else None

        if data_type == "prices":
            df = get_market_prices(ticker_list, period)
        elif data_type == "returns":
            df = get_market_returns(ticker_list, period)
        elif data_type == "volume":
            df = get_market_volume(ticker_list, period)
        else:
            return {"error": f"Unknown data_type '{data_type}'. Use 'prices', 'returns', or 'volume'."}

        if df.empty:
            return {"error": "No data returned. Check your tickers and internet connection."}

        # Convert to JSON-friendly format.
        # Format dates safely.
        if hasattr(df.index, "strftime"):
            dates = df.index.strftime("%Y-%m-%d").tolist()
        else:
            dates = [str(d)[:10] for d in df.index]

        records = []
        for i, date in enumerate(dates):
            row = {"date": date}
            for col in df.columns:
                row[col] = round(float(df.iloc[i][col]), 6)
            records.append(row)

        # Latest values.
        latest = {}
        for col in df.columns:
            latest[col] = round(float(df[col].iloc[-1]), 4)

        return {
            "data_type": data_type,
            "tickers": list(df.columns),
            "rows": len(df),
            "date_range": {
                "start": dates[0] if dates else None,
                "end": dates[-1] if dates else None,
            },
            "latest_values": latest,
            "data": records[-10:],  # Last 10 rows (full data would be too large).
            "note": "Only the last 10 rows are returned. Use a local call for full data.",
        }

    except Exception as error:
        return {"error": f"Market data fetch failed: {error}"}


@app.get("/portfolio-risk")
def get_portfolio_risk(
    tickers: str = "SPY,HYG,TLT,GLD,BTC-USD",
    weights: str = "0.40,0.20,0.20,0.10,0.10",
    period: str = "2y",
):
    """
    Combined portfolio risk analysis: PRI + SRS in one call.

    This is a convenience endpoint that runs both calculate_pri() and
    calculate_srs() and returns the results together, saving the
    dashboard from making two separate API calls.

    Example: /portfolio-risk?tickers=SPY,TLT,GLD&weights=0.5,0.3,0.2

    Example response (truncated):
    {
        "pri": { "pri": 42.7, "risk_level": "Moderate", ... },
        "srs": { "scores": { "SPY": { "srs": 48.2, ... }, ... } }
    }
    """
    try:
        ticker_list = _parse_tickers(tickers)
        weight_list = _parse_weights(weights)
        if weights and weight_list is None:
            return {"error": "Weights must be numbers separated by commas."}

        pri_result = calculate_pri(ticker_list, weight_list, period)
        srs_result = calculate_srs(ticker_list, period=period)

        return {
            "pri": pri_result,
            "srs": srs_result,
        }

    except Exception as error:
        return {"error": f"Portfolio risk analysis failed: {error}"}


@app.get("/srs-gsri")
def get_srs_gsri(
    period: str = "2y",
    rolling_window: int = 60,
):
    """
    Combined SRS + GSRI snapshot in one call.

    Returns the current GSRI, current SRS, sub-scores, and gating state
    all in a single response. This saves the dashboard from making
    three separate calls (/gsri, /srs, /gating).

    Example: /srs-gsri?period=1y

    Example response (truncated):
    {
        "gsri": { "current_gsri": 38.4, "risk_level": "Elevated", ... },
        "srs_current": 34.7,
        "gating": { "level": 0, "label": "Normal", ... }
    }
    """
    try:
        gsri_result = calculate_gsri(period=period, rolling_window=rolling_window)

        if "error" in gsri_result:
            return gsri_result

        # Extract SRS from GSRI result.
        srs_current = gsri_result.get("srs_current", 0)

        # Get gating based on the GSRI.
        gating_result = evaluate_gating(gsri_result["current_gsri"])

        return {
            "gsri": gsri_result,
            "srs_current": srs_current,
            "srs_components": gsri_result.get("srs_components", {}),
            "gating": gating_result,
        }

    except Exception as error:
        return {"error": f"SRS/GSRI computation failed: {error}"}


@app.get("/price-protection")
def get_price_protection_get(
    tickers: str = "SPY,HYG,TLT,GLD,BTC-USD",
    weights: str = "0.40,0.20,0.20,0.10,0.10",
    notional: float = 1_000_000,
    protection_level_pct: float = 20.0,
    duration_days: int = 90,
    period: str = "2y",
):
    """
    Price a crash protection contract (GET version).

    This is an alias for /price with the same functionality.
    Use GET for simple browser-based testing.

    Example: /price-protection?tickers=SPY,TLT&notional=500000&protection_level_pct=15
    """
    ticker_list = _parse_tickers(tickers)
    weight_list = _parse_weights(weights)
    if weights and weight_list is None:
        return {"error": "Weights must be numbers separated by commas."}
    return price_protection(
        ticker_list, weight_list, notional,
        protection_level_pct, duration_days, period,
    )


@app.post("/price-protection")
def post_price_protection(request: ProtectionRequest):
    """
    Price a crash protection contract (POST version).

    Use POST when sending structured JSON data from code:

        import requests
        response = requests.post("http://localhost:8000/price-protection", json={
            "tickers": ["SPY", "TLT", "GLD"],
            "weights": [0.5, 0.3, 0.2],
            "notional": 1000000,
            "protection_level_pct": 20.0,
            "duration_days": 90,
            "period": "2y"
        })
        result = response.json()
    """
    try:
        tickers = [t.strip().upper() for t in request.tickers]
        return price_protection(
            tickers, request.weights, request.notional,
            request.protection_level_pct, request.duration_days, request.period,
        )
    except Exception as error:
        return {"error": f"Protection pricing failed: {error}"}


@app.get("/run-waterfall-stress-test")
def get_waterfall_stress_test(
    event_magnitude: float = Query(
        default=500_000_000,
        description="Hypothetical loss amount in dollars (e.g., 500000000 for $500M)",
        gt=0,
    ),
    defaulter_initial_margin: float = Query(default=200_000_000, description="Layer 1: Defaulter margin ($)"),
    defaulter_default_fund: float = Query(default=50_000_000, description="Layer 2: Defaulter fund ($)"),
    defaulter_contingent_capital: float = Query(default=30_000_000, description="Layer 3: Contingent capital ($)"),
    mutualized_default_fund: float = Query(default=500_000_000, description="Layer 4: Mutualized fund ($)"),
    srx_clearinghouse_capital: float = Query(default=150_000_000, description="Layer 5: SRX capital ($)"),
):
    """
    Run a clearinghouse stress test by event magnitude.

    This sends a hypothetical loss amount through the 5-layer default
    waterfall and reports the status of each layer.

    Example: /run-waterfall-stress-test?event_magnitude=1000000000

    Example response (truncated):
    {
        "waterfall_result": {
            "loss_amount": 1000000000,
            "total_capacity": 930000000,
            "breach": true,
            "unabsorbed_loss": 70000000,
            "layers": [
                {"layer": 1, "name": "Defaulter Initial Margin",
                 "available": 200000000, "absorbed": 200000000, "status": "EXHAUSTED"},
                ...
            ]
        },
        "event_label": "$1.0B"
    }
    """
    try:
        result = waterfall_stress_test(
            event_magnitude=event_magnitude,
            defaulter_initial_margin=defaulter_initial_margin,
            defaulter_default_fund=defaulter_default_fund,
            defaulter_contingent_capital=defaulter_contingent_capital,
            mutualized_default_fund=mutualized_default_fund,
            srx_clearinghouse_capital=srx_clearinghouse_capital,
        )

        if "error" in result:
            return result

        # Convert the summary DataFrame to a serializable format.
        if "summary_df" in result and hasattr(result["summary_df"], "to_dict"):
            result["summary_df"] = result["summary_df"].to_dict(orient="records")

        return result

    except Exception as error:
        return {"error": f"Waterfall stress test failed: {error}"}
